twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_theme: ['bootstrap_4_layout.html.twig', 'form_theme/textearea_custom.html.twig']
