#index:
#    path: /
#    controller: App\Controller\DefaultController::index

task:
    path: /task
    controller: App\Controller\TaskController::index
    methods: [GET|POST]

show:
    path: /task/show/{id?}
    controller: App\Controller\TaskController::show

create:
    path: /task/create
    controller: App\Controller\TaskController::create

