#index:
#    path: /
#    controller: App\Controller\DefaultController::index

task:
  path: /task
  controller: App\Controller\TaskController::index

show:
  path: /task/{id}
  controller: App\Controller\TaskController::show
  requirements:
    id: '\d+'
