#index:
#    path: /
#    controller: App\Controller\DefaultController::index

task_index:
    path: /task
    controller: App\Controller\TaskController::index
    methods: [GET|POST]

task_show:
    path: /task/show/{id?}
    controller: App\Controller\TaskController::show

task_new:
    path: /task/new
    controller: App\Controller\TaskController::new
    methods: [GET|POST]
