#index:
#    path: /
#    controller: App\Controller\DefaultController::index

lista:
    path: /lista
    controller: App\Controller\TaskController::index
    methods: [GET|POST]

show:
    path: /task/show/{id?}
    controller: App\Controller\TaskController::show
    condition:  "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/Chrome/i'"
