#index:
#    path: /
#    controller: App\Controller\DefaultController::index

task:
  path: /task
  controller: App\Controller\TaskController::index

show:
  path: /task/show/{id?}
  controller: App\Controller\TaskController::show
  defaults:
    id: 10
  requirements:
    id: '\d+'
