#index:
#    path: /
#    controller: App\Controller\DefaultController::index

task_index:
    path: /index
    controller: App\Controller\TaskController::index

task_show:
    path: /task/show/{id?}
    controller: App\Controller\TaskController::show

task_new:
    path: /task/new
    controller: App\Controller\TaskController::new

task_edit:
    path: /{id}/edit
    controller: App\Controller\TaskController::edit
